/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_opensearch_neuralsearch_jni_NativeVsagService */

#ifndef _Included_org_opensearch_neuralsearch_jni_NativeVsagService
#define _Included_org_opensearch_neuralsearch_jni_NativeVsagService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_init
  (JNIEnv *, jobject);

/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    createIndex
 * Signature: (Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_createIndex
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    add
 * Signature: (JLorg/opensearch/neuralsearch/jni/VsagDataset;)Z
 */
JNIEXPORT jlongArray JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_add
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    serializeIndex
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_serializeIndex
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    deserializeIndex
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_deserializeIndex
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    knnSearch
 * Signature: (JLorg/opensearch/neuralsearch/jni/VsagSparseDataset;ILjava/lang/String;)[Lorg/opensearch/neuralsearch/jni/VsagSearchResult;
 */
JNIEXPORT jobjectArray JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_knnSearch
  (JNIEnv *, jobject, jlong, jobject, jint, jstring);

/*
 * Class:     org_opensearch_neuralsearch_jni_NativeVsagService
 * Method:    cleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_opensearch_neuralsearch_jni_NativeVsagService_cleanup
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
